[package]
name = "agilang-build"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
agilang-source = { path = "../agilang-source" }
agilang-types = { path = "../agilang-types" }
agilang-symbols = { path = "../agilang-symbols" }
agilang-ir = { path = "../agilang-ir" }
agilang-compiler = { path = "../agilang-compiler" }
agilang-codegen-c = { path = "../agilang-codegen-c" }
agilang-linker = { path = "../agilang-linker" }
agilang-framework-server = { path = "../agilang-framework-server" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
