[package]
name = "agilang-framework-server"
version.workspace = true
edition.workspace = true

[dependencies]
agilang-framework-http = { path = "../agilang-framework-http" }
agilang-framework-routing = { path = "../agilang-framework-routing" }
agilang-framework-view = { path = "../agilang-framework-view" }
agilang-framework-core = { path = "../agilang-framework-core" }
agilang-framework-config = { path = "../agilang-framework-config" }
agilang-framework-auth = { path = "../agilang-framework-auth" }
agilang-framework-database = { path = "../agilang-framework-database" }
agilang-framework-validation = { path = "../agilang-framework-validation" }
agilang-database-agidb = { path = "../agilang-database-agidb" }
agilang-database-driver = { path = "../agilang-database-driver" }
agilang-runtime-crypto = { path = "../agilang-runtime-crypto" }
agilang-runtime-http = { path = "../agilang-runtime-http" }
agilang-runtime-async = { path = "../agilang-runtime-async" }
agilang-runtime-webrtc = { path = "../agilang-runtime-webrtc" }
chrono = "0.4"
serde.workspace = true
serde_json = "1"
anyhow.workspace = true
base64.workspace = true
sha1 = "0.10"
tokio.workspace = true
uuid = { version = "1.11", features = ["v4"] }

[dev-dependencies]
agilang-framework-migrations = { path = "../agilang-framework-migrations" }
agilang-project-generator = { path = "../agilang-project-generator" }
