[package]
name = "agilang-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
agilang-source = { path = "../agilang-source" }
agilang-diagnostics = { path = "../agilang-diagnostics" }
agilang-lexer = { path = "../agilang-lexer" }
agilang-ast = { path = "../agilang-ast" }
agilang-parser = { path = "../agilang-parser" }
agilang-types = { path = "../agilang-types" }
agilang-symbols = { path = "../agilang-symbols" }
agilang-ir = { path = "../agilang-ir" }
agilang-semantic = { path = "../agilang-semantic" }
anyhow.workspace = true
