[package]
name = "agilang-runtime-http"
version.workspace = true
edition.workspace = true

[dependencies]
agilang-runtime-core = { path = "../agilang-runtime-core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
