[package]
name = "agilang-database-mysql-gateway"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
agilang-database-agidb = { path = "../agilang-database-agidb" }
agilang-database-driver = { path = "../agilang-database-driver" }
agilang-database-parser = { path = "../agilang-database-parser" }
agilang-framework-auth = { path = "../agilang-framework-auth" }
