[package]
name = "agilang-database-mysql-gateway"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
agilang-database-parser = { path = "../agilang-database-parser" }
agilang-database-prepared = { path = "../agilang-database-prepared" }
agilang-database-policy = { path = "../agilang-database-policy" }
