[package]
name = "agilang-blockchain-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agilang-runtime-core = { path = "../agilang-runtime-core" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
